### ISSUE TITLE
Read the docs builds broken

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#1408]
PR Build failed on unrelated change https://readthedocs.org/projects/grand-challengeorg/builds/11305924/

```
Running Sphinx v1.8.5
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/grand-challengeorg/envs/1407/lib/python3.8/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/grand-challengeorg/envs/1407/lib/python3.8/site-packages/sphinx_autodoc_typehints.py", line 8, in <module>
    from sphinx.util.inspect import signature as Signature
ImportError: cannot import name 'signature' from 'sphinx.util.inspect' (/home/docs/checkouts/readthedocs.org/user_builds/grand-challengeorg/envs/1407/lib/python3.8/site-packages/sphinx/util/inspect.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/grand-challengeorg/envs/1407/lib/python3.8/site-packages/sphinx/cmd/build.py", line 300, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/docs/checkouts/readthedocs.org/user_builds/grand-challengeorg/envs/1407/lib/python3.8/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/grand-challengeorg/envs/1407/lib/python3.8/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/grand-challengeorg/envs/1407/lib/python3.8/site-packages/sphinx/registry.py", line 475, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
sphinx.errors.ExtensionError: Could not import extension sphinx_autodoc_typehints (exception: cannot import name 'signature' from 'sphinx.util.inspect' (/home/docs/checkouts/readthedocs.org/user_builds/grand-challengeorg/envs/1407/lib/python3.8/site-packages/sphinx/util/inspect.py))

Extension error:
Could not import extension sphinx_autodoc_typehints (exception: cannot import name 'signature' from 'sphinx.util.inspect' (/home/docs/checkouts/readthedocs.org/user_builds/grand-challengeorg/envs/1407/lib/python3.8/site-packages/sphinx/util/inspect.py))
```

**Comment by jmsmkn** [comment]
There was a new version of sphinx_autodoc_typehints (1.11.0) which might have broken this.

**Comment by jmsmkn** [comment]
Likely - in https://github.com/agronholm/sphinx-autodoc-typehints/pull/138 support for Sphinx < 3.0 was dropped, and for some reason read the docs pins sphinx to version `sphinx<2`.
