### ISSUE TITLE
Unhandled `TooManyJobsScheduled` when running a normal algorithm job

### ISSUE THREAD

**Issue by jmsmkn** [comic/grand-challenge.org#2852]
In task `grandchallenge.algorithms.tasks.execute_algorithm_job`:

```
Traceback (most recent call last):
File "/opt/poetry/.venv/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
R = retval = fun(*args, **kwargs)
File "/opt/poetry/.venv/lib/python3.10/site-packages/sentry_sdk/integrations/celery.py", line 231, in _inner
reraise(*exc_info)
File "/opt/poetry/.venv/lib/python3.10/site-packages/sentry_sdk/_compat.py", line 60, in reraise
raise value
File "/opt/poetry/.venv/lib/python3.10/site-packages/sentry_sdk/integrations/celery.py", line 226, in _inner
return f(*args, **kwargs)
File "/opt/poetry/.venv/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
return self.run(*args, **kwargs)
File "/app/grandchallenge/algorithms/tasks.py", line 142, in execute_algorithm_job
raise TooManyJobsScheduled
grandchallenge.algorithms.exceptions.TooManyJobsScheduled
```

**Comment by jmsmkn** [comment]
Given the current load this is now urgent.
