### ISSUE TITLE
make runserver reports an error

### ISSUE THREAD

**Issue by new-bajie** [comic/grand-challenge.org#3262]
I started on Windows platform, wsl2,windows has docker desktop installed

I locate _gc_demo_algorithm, The demo_algorithm_path is incorrect.

docker client.build image execution error:
🔐 Setting up minio 🔐
mc: Configuration written to `/home/django/.mc/config.json`. Please update your access credentials.
mc: Successfully created `/home/django/.mc/share`.
mc: Initialized share uploads `/home/django/.mc/share/uploads.json` file.
mc: Initialized share downloads `/home/django/.mc/share/downloads.json` file.
Added `local` successfully.
Access permission for `local/grand-challenge-public` is set from `/tmp/tmpu_8ak96_/public_read.json`
Added `local` successfully.
Created policy `components` successfully.
Added user `componentstask` successfully.
Attached Policies: [components]
To User: componentstask
✨ Minio set up ✨
🔨 Creating development fixtures 🔨
/app
/app/tests/resources/gc_demo_algorithm
['copy_io.py', 'Dockerfile']
Exception while running run() in 'scripts.development_fixtures'
Traceback (most recent call last):
  File "/app/manage.py", line 21, in <module>
    main()
  File "/app/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/opt/poetry/.venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/poetry/.venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/poetry/.venv/lib/python3.11/site-packages/django_extensions/management/email_notifications.py", line 65, in run_from_argv
    super().run_from_argv(argv)
  File "/opt/poetry/.venv/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/poetry/.venv/lib/python3.11/site-packages/django_extensions/management/email_notifications.py", line 77, in execute
    super().execute(*args, **options)
  File "/opt/poetry/.venv/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/poetry/.venv/lib/python3.11/site-packages/django_extensions/management/utils.py", line 62, in inner
    ret = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/poetry/.venv/lib/python3.11/site-packages/django_extensions/management/commands/runscript.py", line 281, in handle
    run_script(script_mod, *script_args)
  File "/opt/poetry/.venv/lib/python3.11/site-packages/django_extensions/management/commands/runscript.py", line 159, in run_script
    exit_code = mod.run(*script_args)
                ^^^^^^^^^^^^^^^^^^^^^
  File "/app/scripts/development_fixtures.py", line 91, in run
    algorithm = _create_algorithm_demo(users)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/scripts/development_fixtures.py", line 371, in _create_algorithm_demo
    with _gc_demo_algorithm() as container:
  File "/usr/local/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/app/scripts/algorithm_evaluation_fixtures.py", line 174, in _gc_demo_algorithm
    docker_client.build_image(
  File "/app/grandchallenge/components/backends/docker_client.py", line 55, in build_image
    return _run_docker_command(
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/grandchallenge/components/backends/docker_client.py", line 40, in _run_docker_command
    return  run(
            ^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/bin/sh', '-c', 'docker build --platform linux/amd64 --tag fixtures-algorithm-io:latest /app/tests/resources/gc_demo_algorithm']' returned non-zero exit status 1.
make: *** [Makefile:101: development_fixtures] Error 1

**Comment by jmsmkn** [comment]
Please use the latest commit of the main branch.

**Comment by jmsmkn** [comment]
We cannot reproduce this error. It would be best to work out _why_ the docker command is failing, look at the captured stderr, etc. Please check your installation.

**Comment by new-bajie** [comment]
@jmsmkn How to configure the environment for wsl2 windows docker
